name: Auto approve

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/actions/github/auto-approve@auto-approve-and-auto-merge
        if: contains(github.event.pull_request.labels.*.name, 'auto-approve')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
