name: Auto merge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  check_run:
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/actions/github/auto-merge@auto-approve-and-auto-merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: auto-merge,!wip
          UPDATE_LABELS: auto-merge
          # 1 minute sleep between merge retries due to how long terratest can take
          # because by default this GH action will retry 60 times it will fail after 1h
          # MERGE_RETRY_SLEEP: 60000
          # MERGE_RETRIES: 60
          MERGE_METHOD: "squash"
          UPDATE_METHOD: "rebase"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_FORKS: "false"
          MERGE_DELETE_BRANCH: "true"
